### ISSUE TITLE
Feature Request: Change color of character when `--use-icons` used

### ISSUE THREAD

**Issue by psynyde** [fdw/rofimoji#201]
as the title suggests is there any possibility to change font color with icons as they're tough to see when using dark theme for example.
![image](https://github.com/user-attachments/assets/cf8735c0-cf0a-4987-b921-dcc123038efd)

**Comment by fdw** [comment]
Have you tried a different theme or setting it the font color explicitly?

**Comment by PsyNyde** [comment]
> Have you tried a different theme or setting it the font color explicitly?

1st of all, Sorry for a quite late reply.

![image](https://github.com/user-attachments/assets/f002bfa7-25d1-4360-b51c-ce7cfc10858b)

this is the rasi code i'm using to replicate the image above.

```css
configuration {
     show-icons: true;
}
 textbox {
     vertical-align: 0.5;
     horizontal-align: 0.5;
}
 listview {
     columns: 7;
     lines: 9;
     cycle: false;
     dynamic: false;
     layout: vertical;
     flow: horizontal;
     reverse: false;
     fixed-height: true;
     fixed-columns: true;
}
 element {
     orientation: vertical;
     padding: 3px;
     text-color: #f0f0f0;
}
 element selected.normal {
     background-color: #202020;
     border-radius: 5px;
}
 element-icon {
     background-color: transparent;
     text-color: #f0f0f0;
     size: 24px;
     vertical-align: 0.5;
     horizontal-align: 0.5;
}
 element-text {
     enabled: false;
     text-color: #f0f0f0;
}
```

as you can see i've used text-color on every element related classes but still the font color is black.

my assumtion is you need to add text-color properties in [this](https://github.com/fdw/rofimoji/blob/28fa9fbc2c3e6c026c73d4e07d5174a2296f2d6e/src/picker/selector/rofi.py#L87) span tag but idk if it's possible as rofi doesn't follow usual css/html rules afaik
